#### Support Vector Regression

In [2]:
## Dataset (Tips Dataset)
import seaborn as sns
df = sns.load_dataset('tips')

In [3]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [5]:
df['sex'].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [6]:
df['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [7]:
df['smoker'].value_counts()

smoker
No     151
Yes     93
Name: count, dtype: int64

In [8]:
df['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [9]:
## Independent and Dependent Features

X = df[['tip','sex','smoker','day','time','size']]
y = df['total_bill']

In [10]:
## train test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.25,random_state = 10)

In [16]:
X_train.head()

      tip   sex smoker  day    time  size
58   1.76  Male    Yes  Sat  Dinner     2
1    1.66  Male     No  Sun  Dinner     3
2    3.50  Male     No  Sun  Dinner     3
68   2.01  Male     No  Sat  Dinner     2
184  3.00  Male    Yes  Sun  Dinner     2

#### Feature encoding(Label encoding and Onehot Encoding)

In [17]:
from sklearn.preprocessing import LabelEncoder

In [18]:
le1 = LabelEncoder()
le2 = LabelEncoder()
le3 = LabelEncoder()

In [19]:
X_train['sex'] = le1.fit_transform(X_train['sex'])
X_train['smoker']=le2.fit_transform(X_train['smoker'])
X_train['time'] = le3.fit_transform(X_train['time'])

In [20]:
X_train.head()

      tip  sex  smoker  day  time  size
58   1.76    1       1  Sat     0     2
1    1.66    1       0  Sun     0     3
2    3.50    1       0  Sun     0     3
68   2.01    1       0  Sat     0     2
184  3.00    1       1  Sun     0     2

In [21]:
X_test['sex'] = le1.transform(X_test['sex'])
X_test['smoker'] = le2.transform(X_test['smoker'])
X_test['time'] = le3.transform(X_test['time'])

In [22]:
X_test.head()

      tip  sex  smoker  day  time  size
162  2.00    0       0  Sun     0     3
60   3.21    1       1  Sat     0     2
61   2.00    1       1  Sat     0     2
63   3.76    1       1  Sat     0     4
69   2.09    1       1  Sat     0     2

In [23]:
## Onehot Encoding ----> ColumnTransformer

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [26]:
ct = ColumnTransformer(transformer=[('onehot', OneHotEncoder(drop = 'first'),3)],
remainder='passthrough')

TypeError: ColumnTransformer.__init__() got an unexpected keyword argument 'transformer'